* Emacs flashcards with org-mode and org-drill

** Keybindings

*** Exercise 1  :drill:
SCHEDULED: <2021-11-09 ter>
:PROPERTIES:
:ID:       74acbb92-63f6-4856-bc45-cb2a97811422
:DRILL_LAST_INTERVAL: 11.1407
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.7
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:49]
:END:

In general, how to open a file in Emacs?

**** The Answer

Execute command =find-file= which is bounded to =C-x C-f=.

*** Exercise 2  :drill:
SCHEDULED: <2021-11-09 ter>
:PROPERTIES:
:ID:       26f20950-7616-47af-8475-8c4087d0cdbe
:DRILL_LAST_INTERVAL: 11.1407
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.7
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:49]
:END:

In general, how to close Emacs?

**** The Answer

Execute command =save-buffers-kill-terminal= which is bounded to  =C-x C-c=.

*** Exercise 3                                                  :drill:dired:
SCHEDULED: <2021-11-09 ter>
:PROPERTIES:
:ID:       8bb25e92-f297-45de-ba11-3ef2e964b82e
:DRILL_LAST_INTERVAL: 11.1407
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.7
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:49]
:END:

In dired, how to open dired?

**** The Answer

Execute command =dired= which is bounded to =C-x d=.

*** Exercise 4                                                  :drill:dired:
SCHEDULED: <2021-11-09 ter>
:PROPERTIES:
:ID:       1f80afc2-cab4-4634-9c12-1a1ce18bd716
:DRILL_LAST_INTERVAL: 11.1407
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.7
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:49]
:END:

In dired, how to close dired?

**** The Answer

=q=

*** Exercise 5 :drill:move:
SCHEDULED: <2021-11-09 ter>
:PROPERTIES:
:ID:       f5690057-e0b4-4132-8936-f566cfd30c59
:DRILL_LAST_INTERVAL: 10.764
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 4.5
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:51]
:END:

In lisp file, how to move to the next s-expression?

**** Answer

=C-M-f=

*** Exercise 6 :drill:move:
SCHEDULED: <2021-11-09 ter>
:PROPERTIES:
:ID:       653842f2-504b-4a6b-b2d5-c03841b41702
:DRILL_LAST_INTERVAL: 11.1407
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 5.0
:DRILL_EASE: 2.7
:DRILL_LAST_QUALITY: 5
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:49]
:END:

In lisp file, how to move to the previous s-expression?

**** Answer

=C-M-b=

*** Exercise 7 :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       0cefa81d-728e-49f8-a209-a35bdd283608
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 3
:DRILL_FAILURE_COUNT: 1
:DRILL_AVERAGE_QUALITY: 3.667
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

In org, how to move to the next org heading (not in the same level)?

**** Answer

=C-c C-n=

*** Exercise 8                                                    :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       3d24c0cd-ba5d-43e6-9c71-0c02a4477610
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 3
:DRILL_FAILURE_COUNT: 1
:DRILL_AVERAGE_QUALITY: 3.333
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

In org, how to move to the previous org heading (not in the same level)?

**** Answer

=C-c C-p=

*** Exercise 9                                                    :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       4c310942-ba73-4634-ba24-99b42ab959a6
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 4
:DRILL_FAILURE_COUNT: 2
:DRILL_AVERAGE_QUALITY: 3.0
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

In org, how to move to the next org heading in the same level?

**** Answer

=C-c C-f=

*** Exercise 10                                                   :drill:org:
SCHEDULED: <2021-11-08 seg>
:PROPERTIES:
:ID:       36fd9aaf-32d1-45ef-a915-5e36f06cda43
:DRILL_LAST_INTERVAL: 10.3873
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 3
:DRILL_FAILURE_COUNT: 1
:DRILL_AVERAGE_QUALITY: 3.333
:DRILL_EASE: 2.46
:DRILL_LAST_QUALITY: 3
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:51]
:END:

In org, how to move to the previous org heading in the same level?

**** Answer

=C-c C-b=


*** Exercise 11 :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       30abcea9-9258-4086-803c-fb7157bc828a
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 4
:DRILL_FAILURE_COUNT: 2
:DRILL_AVERAGE_QUALITY: 3.25
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

In org, how to move to the next item of the list?

**** Answer

=S down=

*** Exercise 12 :drill:dired:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       e3383d31-86e9-49b3-be56-1c9ee6b1621b
:DRILL_LAST_INTERVAL: 4.14
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 3
:DRILL_FAILURE_COUNT: 1
:DRILL_AVERAGE_QUALITY: 3.0
:DRILL_EASE: 2.6
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

In dired, how to move to the parent directory?

**** Answer

=^=

*** Exercise 13                                                   :drill:org:
SCHEDULED: <2021-11-08 seg>
:PROPERTIES:
:ID:       503b9f61-8706-41bb-84c7-bce62a8a1998
:DRILL_LAST_INTERVAL: 10.0
:DRILL_REPEATS_SINCE_FAIL: 3
:DRILL_TOTAL_REPEATS: 2
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 4.0
:DRILL_EASE: 2.5
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:50]
:END:

How to move to the previous element of
the list in an org file?

**** Answer

=S up=

*** Exercise 14                                                   :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       094476b5-bd9d-4f87-be3e-a684eab9b625
:DRILL_LAST_INTERVAL: 4.0
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 4.0
:DRILL_EASE: 2.5
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

How to indent a s-expression?
Someting like fill-paragraph but for s-expressions?

**** Answer
=C-M-q= which is bounded to =indent-pp-sexp=.

*** Exercise 15                                                   :drill:org:

Suppose you have a phrase with multiple white-spaces at the beginning
of the line:

"          This is an example with a lot of white-space."

How to remove **all** the white-spaces in the beginning?

**** Answer

Execute command =delete-horizontal-space= which is bounded to =M-\=.
Observation: In my notebook, with Portuguese keyboard you need to
press "Alt -" to get the "\" character.


*** Exercise 16                                                   :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       3a227762-2f89-4cb6-8663-fcfd8fa50dbb
:DRILL_LAST_INTERVAL: 4.0
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 4.0
:DRILL_EASE: 2.5
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

How to move the point from the beginning of the line until the first character?

**** Answer

=M-m= which is bounded to =back-to-indentation=

*** Exercise 17                                                   :drill:org:
SCHEDULED: <2021-11-02 ter>
:PROPERTIES:
:ID:       bd74c351-9dbc-4afd-a008-9261a6b3b12f
:DRILL_LAST_INTERVAL: 4.0
:DRILL_REPEATS_SINCE_FAIL: 2
:DRILL_TOTAL_REPEATS: 1
:DRILL_FAILURE_COUNT: 0
:DRILL_AVERAGE_QUALITY: 4.0
:DRILL_EASE: 2.5
:DRILL_LAST_QUALITY: 4
:DRILL_LAST_REVIEWED: [2021-10-29 sex 14:52]
:END:

In Slime, how to inspect the object without needing to right click with the mouse?

**** Answer

=C-c C-v C-i= which is bounded to =slime-presentation-at-point=

*** Exercise 18                                                   :org:

How to fix a word using flyspell and not touching the mouse?

**** Answer

=C-c $= which is bounded to
=flyspell-correct-word-before-point=. There are multiple commands
related to the "prefix" =flyspell-correct-word...=.

*** Exercise 19                                                   :drill:org:
:PROPERTIES:
:ID:       b6f646fc-f486-489b-bdf8-f58f97c5dfac
:END:
How to transpose characters?

**** Answer

=C t=.

*** Exercise 20                                                   :drill:org:
:PROPERTIES:
:ID:       5a740609-3498-4517-a307-8e57ff7c36d9
:END:
How to transpose words?

**** Answer

=M t=. The exact position of the point (mark or cursor) is hugely important.

*** Exercise 21                                                   :drill:org:
:PROPERTIES:
:ID:       41282f8c-2f45-4cdb-a3b6-48d07d084f68
:END:
How to transpose s-expressions?

**** Answer

=C M t=. The exact position of the point (mark or cursor) is hugely important.

*** Exercise 22                                                   :drill:org:
:PROPERTIES:
:ID:       38894203-cc3c-4cb6-bf0e-aa8a5444452d
:END:
How to transpose lines?

**** Answer

=C x C t=. The exact position of the point (mark or cursor) is hugely important.

*** Exercise 23

How to make the org-clock calculate the delta of the intervl `=>'?

This is specially useful after manually changing the raw file which is
automatically written.

**** Answer

Execute command =org-clock-update-time-maybe=.

*** Exercise 24

How to uppercase **only** the first letter of a word. This is also
called capitalizing words. For instance, changing from "lisp"->"Lisp"?

**** Answer

Execute command =capitalize-word= which is bounded to =M-c=.

*** Exercise 25

How to uppercase the whole word?
or instance, move "lisp" -> "LISP".

**** Answer

Execute command =upcase-word= which is bounded to =M-u=.

*** Exercise 26

How to lowercase the whole word?
For instance, move "LISP" -> "lisp".

**** Answer

Execute command =downcase-word= which is bounded to =M-l=.

*** Exercise 27

How to find out the problematic parens in a Elisp or Common Lisp file?

**** Answer

Execute the command =check-parens=. The cursor will be placed on the
problematic parenthesis.

*** Exercise 28

There are multiple white-spaces between two words.  Such as "first
second". How to turn the space between them to be just one whitespace?

**** Answer

Execute command =just-one-space= which is bounded to =M-SPC=. Really useful one!

*** Exercise 29

Suppose you want to delete everything until a certain character and including this character.
For instance, on the phrase below:

"               Pernambuco has some cool things"

Delete everything leaving just "as some cool things".

**** Answer

Execute command =zap-to-char= which is bounded to =M-z=.

*** Exercise 30

Emacs has a *default* clipboard ring tool. To "copy" something, the
user just needs to press =M-w=. To "paste" (yank) something, just use
=C-y=. To "cut" (kill), just to do =C-w=. Everything copied and cut
(killed), goes to the clipboard ring.

Suppose you copied "A", killed "B", copied "C", and killed "D".

How to iterate everything you copied?

**** Answer

Execute command =yank-pop= which is bounded to =M-y=, after pressing
=C-y=. It will cycle through kill ring after yanking.

*** Exercise 31

How to downcase a region?

**** Answer

Execute command =downcase-region= which is bounded to =C-x C-l=.

*** Exercise 32

How to remove all blank lines in a region or buffer?

**** Answer

Execute command =M-x flush-lines RET ^$ RET=.

*** Exercise 33

Using shell in Emacs, how to open a file in the current application
instead of another application?

**** Answer

Use =$ emacsclient README.org=.

*** Exercise 34

How to "refresh a buffer" in Emacs?

**** Answer

Use =revert buffer= which is binded in my config to =C-x C-M-r=.

*** Exercise 35

How to go to the last marked placed =C-SPC=?

**** Answer

Just do =C-u C-SPC=. Observation: I do not know this command name.

*** Exercise 36

How to remove whitespace in the beginning of lines?

**** Answer

Mark the region and just do =delete-whitespace-rectangle=.

*** Exercise 37

How to do a great ripgrep inside Emacs?

**** Answer

Use `counsel-projectile-rg` which is bounded to =C-c p s r=. This is
the killer feature of projectile!

*** Exercise 38

How to delete whitespaces after the last character (aka trailing
whitespace) in every line?

**** Answer

Use =delete-trailing-whitespace= (unbounded).

*** Exercise 39

What is the number #1 command for Magit to show you where you are?

**** Answer

Use =magit-status= (=C-x g=).

*** Exercise 40

In Magit, how to pull out the stash list?

**** Answer

Hit =z= which is bounded to Stash.

*** Exercise 41

In Magit, how to stash both the index **and** the work tree?

**** Answer

Hit =z= again (after initial =z= to stash). This will stage all the
files that are know by Git.

*** Exercise 42

The killer feature of Projectile is known as
`counsel-projectile-rg'. The "rg" part stands for "rip grep". What is
the binding?

**** Answer

Hit =C-c p s r=.

*** Exercise 43

Projectile has a binding prefix for all commans. What is this prefix?

**** Answer

Hit =C-c p=. All other commands are a combo on top of this.

*** Exercise 44

In org mode, how to cycle between different visibilities types?
Ex.: only first line (*), then (* and **), and so on.

**** Answer

Hit =Shift-TAB= to execute =org-shiftab= command.

*** Exercise 45

How to create a new heading at the same indentation level?

**** Answer

Hit =C-return= which is bounded to =org-insert-heading-respect-content=.

*** Exercise 46

How to move a heading up in the file considering only the *the same
level of heading hierarchy*?

**** Answer

Hit =M-up= which is bounded to =org-metaup=. The =up= key needs the up
arrow key. To move down, use =M-down=.

*** Exercise 47

How to move /any/ heading up and down in the file *independent* of the heading hierarchy?

**** Answer

Hit =M-shift-up= and =M-shift-down= which is bounded to
=org-shiftmetaup= and =org-shiftmetadown=. Remember to use the arrow
keys =up= and =down=.

*** Exercise 48

How to create a hyperlink in org?

**** Answer

Hit =C-c C-l= which is bounded to =org-insert-link=.

*** Exercise 49

Suppose you have:

- [ ] First item

And you want to have:

- [ ] First item
- [ ]

What do you need to press?

**** Answer

=M-shift-return= to execute =org-insert-todo-heading=.

*** Exercise 50

If you an empty list:

-

How to create an empty check-box?

- [ ]
-

**** Answer

Just press =M-shift-enter= which is bounded to
=org-insert-todo-heading=.

*** Exercise 51

How to open a link on org-mode?

**** Answer

Press =C-c C-o= which is bounded to =org-open-at-point=.

*** Exercise 52

How to automatically reformat org-tables?

E.g., from:

| age| name    |
|28|pedro

To:

| age | name  |
|  28 | pedro |

**** Answer

Just hit =TAB=.

*** Exercise 53

How to create a sub-item in a list?

For instance, from:

- first item

To:

- first item
-

**** Answer

Just hit =M-return= which is bounded to =org-meta-return=.
It also works for numbered lists, such as:

1. first (press =M-return=), and "2." is going to be created:
2.

*** Exercise 54

How to check a check-box?

From:

- [ ] first item

To:

- [X] first item

**** Answer

Just hit =C-c C-x C-b= which is bounded to =org-toggle-checkbox=. By
the way, it also works to un-check the check box.

*** Exercise 55

How to insert code in the .org file?

**** Answer

Insert:

#+begin_src emacs-lisp
  (defun place-holder ()
    (message "hello"))
#+end_src

It is possible to evaluate this with =C-x C-e= (which is bounded to
=eval-last-sexp=).

*** Exercise 56

Suppose you have the following:

#+begin_src txt
    bla bla bla
    cla cla cla
    dla dla dla
#+end_src txt

And you wish to make:

#+begin_src txt
    + bla bla bla
    + cla cla cla
    + dla dla dla
#+end_src txt

How do you achieve this?

**** Answer

Execute =org-ctrl-c-minus= which is bounded to =C-c -=.

*** Exercise  57

Using Paredit, how to do /slurping/ such as:

> (+ 1 2 3 4)

Be

> (+ 1 2 (3) 4)

**** Answer

Execute =paredit-wrap-round= which is bounded to =M-(=.

*** Exercise 58

What is the difference between shell-mode and term-mode?

**** Answer

=term-mode= is like the real terminal in your emacs, like =C-x k= does
*not* even work initially to kill the buffer. You need to exit the
terminal first. =shell-mode= on the other hand is cooler because it
really feels like emacs. Using the docstrings.

=term-mode=: Major mode for interacting with an inferior interpreter.
The interpreter name is same as buffer name, sans the asterisks.

=shell-mode=: Major mode for interacting with an inferior shell.

*** Exercise 59

How to eval an elisp expression on the mini-buffer?

**** Answer

Execute =eval-expression= which is bounded to =M-:=.

*** Exercise 60

Executing =htop= on =*shell*= will not work. It is possible to execute
=htop= on =term-mode=. But =term-mode= is not really
comfortable. There is an alternative for it, like an Emacs built in
"process-mode". What is the command?

**** Answer

The command name is =proced= and there is not a default keybinding.

*** Exercise 61

How to indent a line?

**** Anwer

Press =TAB=.

*** Exercise 62

How to delete all the big space in the middle?

From:

a aa aaa aaaa aaaaa                 b bb bbb bbbb bbbbbb

To:

a aa aaa aaaa aaaaab bb bbb bbbb bbbbbb

**** Answer

Execute =M-\= which is bounded to =delete-horizontal-space=.  This is
hard on my config, because to generate "\" is necessary to press right
alt (also known as Alt-graphic) and the "-" (hifen) character. So, to
the execute this command, it is necessary to press
=M-Altgraphic-hifen= (or =M-Altgraphic--=).

*** Exercise 63

How to use dabbrev-expand? The cool built-in auto-complete available
in Emacs that expands the previous word dynamically?

**** Answer

Execute =M-/=. But, to do so it is necessary to use both Alt keys, the
Meta and the Alt-graphic key, so =M-Altgraphic-q=.

*** Exercise 64

How to describe a key?

**** Answer

Execute =C-h k= to do helpful-key.

*** Exercise 65

How to describe a function?

**** Answer

Execute =C-h f= which is bounded to .

*** Exercise 66

It is possible to see all buffers with =list-buffers=. But, there is a
better interface with an improved aesthetics. What is the command?

**** Answer

=ibuffer=!

*** Exercise 67

How to move a file using Dired?

**** Answer

Use =m= to mark a file. And capital =R= to move the file from a new
destination.

***  Exercise 68

How to do a git clone to a new repo being inside Magit?

Obs.: Do not use the terminal

**** Answer

Go to path you want to do the clone. Then, execute =M-x= =magit-clone=.

*** Exercise 69

How to mark a paragraph?

**** Answer

Execute =M-h= which is bounded to =mark-paragraph=.

*** Exercise 70

How to mark a defun?

**** Answer

Execute =C-M-h= which is bounded to =mark-defun=.

***  Exercise 71

How to move in Magit to the same level of heading hierarchy?

**** Answer

Execute =M-n= and =M-p= which are bounded to
=magit-section-backward-sibling= and =magit-section-forward-sibling=.

***  Exercise 72

How to move in Magit to the upper level of heading hierarchy?

**** Answer

Execute =^= which is bounded to =magit-section-up=.

*** Exercise 73

In magit, what is the difference and the similarity between amending
and extending a commit?

**** Answer

Both add information to the immediatly previous commit. But, ammend
add new lines of code and a new commit message. While extend only adds
new lines of code, without changing the commit message.

*** Exercise 74

What is an instant fix-up? What is the relation between an instant
fix-up and doing an interactive rebase?

**** Answer

An instant fix-up allows you to add a commit from the past. An
interactive rebase also allows this. But, an interactive rebase is way
more powerful. Instructions: stage, press to commit, now pick capital
F as an instant fix-up, pick the commit ID you are going to add the
info, and execute C-c. De certa forma, o Fix-up também funciona como
um extend, se o commit do passado for o último.

*** Exercise 75

How to iterate over all the problematic words pointed out by flyspell-mode?

**** Answer

Use =flyspell-go-to-next-error= which is bounded to =C-,=.

*** Exercise 76

Suppose you did some commits on master. But, they should have been put
to a new branch. Now, you want to put those changes on a new branch
and restore master branch.

How to do it with a single command?

**** Answer

With a single command, use the command =new-spin-off= which is bounded
to =s=, and pick a new branch. Then, go back to the original branch,
it will be aligned with the remote version. For this to succeed, there
must be a difference between the remote and the local versions. So,
you should not have done a push!

It is also possible to execute =c= (=create-new-branch=) and then =X=
(=reset=) the main branch. But, this approach takes two steps! Better
use =spin-off=!

*** Exercise 77

Suppose you have a repository under version control, but you want to
keep some files out of the version control. What should you do? How to
do it inside Magit?

**** Answer

First, the file needs to untracked. If it is already being tracked,
remove it from version control using =K= via Magit. Then, press =i= to
ignore it. Not sure about the options on /how/ to ignore. I usually
pick the first option, =t=. This will add the files to the
=.gitignore=.

*** Exercise 78

How move to the beginning and the end of a sentence in Emacs?

**** Answer

Use =M-a= and =M-e=. If it does not work, you might need to change the
value of a specific variable.

*** Exercise 79

In Nyxt, there is =describe-any=. Is there something like that in
Emacs? Something that brings =describe-variable= and
=describe-function= together?

**** Answer

Yes, =describe-any=.

*** Exercise 80

How to do a pomodoro timer on Emacs?

**** Answer

Execute =org-timer-set-timer=.

*** Exercise 81

Before doing an interactive rebase, what should you do?

**** Answer

A back-up branch!

*** Exercise 82

So, you are working in an experimental feature and you want to bring
new changes from main branch. What should you do to bring these
changes?

**** Answer

First, execute to rebase =r=. Then, choose =e=. Finally, type /main/
branch on the mini buffer.

*** Exercise 83

You keep using all the time the command =comment-dwim= to make a code
snippet be treated as a comment. Usually, you do it via =M-x= and
typing. But, there is a default keybinding for it! What is it?

**** Answer

Just press =M-;=.

*** Exercise 84

Cider provides a cool *non-obstrusive* auto-complete, popping out the
options for auto-complete! How to invoke it?

**** Answer

Press =TAB=. Alt-tab would also work... but this is used to change
applications on the Desktop environment.

*** Exercise 85

How to do a =git checkout -f= in Magit?

Note, the point is the force flag =-f=.

**** Answer

Use =Q= which is binded to =magit-git-command= and allow you to
manually type the git command.

*** Exercise 86

How to do a powerfull search on previous data inserted on the CIDER REPL?

**** Answer

Use =C-c M-p= which is bounded to =cider-repl-history=.

*** Exercise 87

How to move files in Emacs?

**** Answer

Use =dired=. First, mark the file with =m=. Then, press =R=. Finally,
the *new* file path location.

*** Exercise 88

In a list of items, how to move one item up in the list?

**** Answer

Use =M-up=. The =up= here is the arrow up key.

*** Exercise 89

How to update a Pull Request putting the new changes from master below
your additions?

**** Answer

I FORGOT HOW TO DO IT ON MAGIT! BUT, I THINK I WILL REMEMBER!!! I
think it is some sort of rebase =git rebease
master/feature-new-whatever=

*** Exercise 90

In dired, how to rename a file?

**** Answer

Use dired andh execute =r=. You can also press =m=, mark multiple
files, and then rename them as a bunch.

Finally, It is always worth mentioning that renaming a file
(especially it's full name, which involves a file path) means *moving*
the file!

*** Exercise 91

How to delete a window in Emacs?

**** Answer

Use =C-x 0= to delete a window.

*** Exercise 92

How to convert an unordered to list an ordered one? Or the opposite?

**** Answer

First change the first item to the deisred form. Then, execute =C-c C-c=.
So,

- cat
- dog
- fish

Tweak the first  
1. cat
- dog
- fish

After pressing =C-c C-c= with cursor on =-=:

1. cat
2. dog
3. fish

The opposite is also true, so tweaking the first:

- cat
2. dog
3. fish

And pressing =C-c C-c=:

- cat
- dog
- fish

*** Exercise 93

In dired, suppose you have pressed =D= to delete some file. How to
undo this?

**** Answer

Put the cursor over that choice and press letter =u= to *remove* the
delete flag.

