* Flashcards to learn about Emacs using org-mode and org-drill

** What is this repository?
   :PROPERTIES:
   :CUSTOM_ID: what-is-this-repository
   :END:

This an open-source repository with flashcards about Emacs. The
flashcard deck here is, basically, an [[https://en.wikipedia.org/wiki/Org-mode][org-mode]] file (=.org=) with
special annotations.

Org-mode files have plain text style with a *simple mark-up* which
means you can comfortably read the source. However, in order to have
the file really behaving like a flashcard system, you need to use
[[https://orgmode.org/worg/org-contrib/org-drill.html][org-drill]] - which is another package from Emacs.

** Why doing this?
   :PROPERTIES:
   :CUSTOM_ID: why-doing-this
   :END:

Emacs is *tough* to learn. Period. However, Emacs is also *awesome* :)

I have been using Emacs almost daily for the last five months and I
still keep learning (loads of) new stuff every week. Moreover, I keep
learning how to improve my old /habits/ and /workflow/. As you
probanly know, in Emacs there are always many ways to achieve the same
end goal but one of the possible paths usually tend to be the faster,
more comfortable or more elegant one.

The keybindings are a especial topic since Emacs is so keyboard
driven.  There are many keystrokes to learn and get used to. Thus, I
think a flashcard tool with spaced repetition approach could be a
great help to boost the memory. Finally, there is nothing more like
true /Emacs hacking/ than using a spaced repetition software program
inside Emacs (=org-mode= and =org-dril=) to improve the learning
process about Emacs!

** Limitations
   :PROPERTIES:
   :CUSTOM_ID: limitations
   :END:

Becoming an Emacs power user is a hard challenge covering different
dimensions. For instance, after Elisp (Emacs lisp) is mastered you
gain super-man powers to change Emacs completely, tinkering it to be
tailor-made for yourself.

This repository does not help with stuff like Elisp hacking and
customization. Actually, this repo is useful for memorization of the
main commands and keybindings.

** How to use it?
   :PROPERTIES:
   :CUSTOM_ID: how-to-use-it
   :END:

You will need to open the =emacs.org= available in this repo using
Emacs. And then, you need to run =org-drill= with =M-x org-drill=.
For more information on how to use Org-drill check this [[https://orgmode.org/worg/org-contrib/org-drill.html][out]].

** Who is this for?
   :PROPERTIES:
   :CUSTOM_ID: who-is-this-for
   :END:

Honestly, this is made by me for me. But maybe it is going to be
useful for other people too! If someone had done such a thing, I would
definitely use it to improve my Emacs skills. It will also serve as my
notes about Emacs.

*** More material
    :PROPERTIES:
    :CUSTOM_ID: more-material
    :END:

Over the last few months, I have come across great material about
Emacs.  Actually, Emacs itself helps a lot with the =describe=,
=info-mode=, and =apropos=. In case you want to check out other
resources, these are the ones I like the most:

- If you are really new to Emacs, check-out the tutorial (execute =M-x
  help-with-tutorial=);
- The book [[https://www.masteringemacs.org/][Mastering Emacs]] is awesome;
- Youtube videos from [[https://www.youtube.com/c/SystemCrafters][System Crafters]] are great, especially the
  playlists: [[https://www.youtube.com/watch?v=74zOY-vgkyw&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ][Emacs from scratch]] and [[https://www.youtube.com/watch?v=48JlgiBpw_I&list=PLEoMzSkcN8oPZvSdewHG8uApD7THlLLCV][The Absolute Beginner Guide to
  Emacs]];
- These GNU [[https://www.gnu.org/software/emacs/refcards/][cheat-sheets]] are also handy;
- This [[https://ankiweb.net/shared/info/2000749682][Anki card]] about Emacs seems to be well-reviewed. Unfortunately,
  I do not have the money to pay for Anki. It could be another good
  resource material if you have the cas$h.

*** Contributions
    :PROPERTIES:
    :CUSTOM_ID: contributions
    :END:

Contributions are welcome! If I happen to really use this repo
consistently adding new content to it and using it for training, it
would already be an utter success. If other people start using it,
making contributions, and adding even more content about Emacs it
would be supreme. Feel free to send a patch :)
